### 3-1. 프로필 조회
GET http://localhost:8081/api/users/profile
Content-Type: application/json
Authorization: {{access_token}}


#### 3-2. 닉네임 수정
PATCH http://localhost:8081/api/users/profiles/nickname
Content-Type: application/json
Authorization: {{access_token}}

{
  "nickname" : "금세"
}


#### 3-3. 비밀번호 수정
PATCH http://localhost:8081/api/users/profiles/password
Content-Type: application/json
Authorization: {{access_token}}

{
  "password": "Password1!",
  "newPassword": "Password2!",
  "confirmNewPassword": "Password2!"
}
