#### 5-1-1. 게시글 등록(지역별)
POST http://localhost:8081/api/boards
Content-Type: application/json
Authorization: {{access_token}}

{
  "title" : "금세 바보 테스트1",
  "subTitle" : "부제목",
  "content" : "나는 나영",
  "category": "지역별",
  "region": "익산"
}

#### 5-1-2. 게시글 등록(분야별)
POST http://localhost:8081/api/boards
Content-Type: application/json
Authorization: {{access_token}}

{
  "title" : "금세 바보 테스트2",
  "subTitle" : "부제목",
  "content" : "테스트2",
  "category": "분야별",
  "section": "정치"
}

#### 5-2. 게시글 조회
GET http://localhost:8081/api/boards/28

#### 5-3-1. 게시글 섹션별 조회 (지역별)
GET http://localhost:8081/api/boards/section?page=1&sortBy=createdAt&sectionType=지역별&sectionName=익산

#### 5-3-2. 게시글 섹션별 조회 (분야별)
GET http://localhost:8081/api/boards/section?page=1&sortBy=createdAt&sectionType=분야별&sectionName=정치

#### 5-4-1. 전체 게시글 조회
GET http://localhost:8081/api/boards/section?page=1&sortBy=createdAt&sectionType=ALL

#### 5-4-2. PICK 게시글 조회
GET http://localhost:8081/api/boards/pick?page=1&sortBy=createdAt

#### 5-4-3. 제목형 게시글 조회
GET http://localhost:8081/api/boards/titles?page=1&sortBy=createdAt

#### 5-4-4. 요약형 게시글 조회
GET http://localhost:8081/api/boards/summaries?page=1&sortBy=createdAt

#### 5-5. 게시글 PICK 지정
PATCH http://localhost:8081/api/boards/14/pick?pick=true
Content-Type: application/json
Authorization: {{access_token}}

#### 5-6. 게시글 수정
PATCH http://localhost:8081/api/boards/2
Content-Type: application/json
Authorization: {{access_token}}

{
  "title" : "제목수정합니다15시44분-2",
  "content" : "수정합니다."
}

#### 5-7. 게시글 삭제
DELETE http://localhost:8081/api/boards/16
Content-Type: application/json
Authorization: {{access_token}}

#### 5-8. 관리자 본인 작성 게시글 조회
GET http://localhost:8081/api/boards/admin?page=1&size=10
Content-Type: application/json
Authorization: {{access_token}}

#### 5-9. 게시글 검색(키워드 넣어서)
GET http://localhost:8081/api/boards/search?keyword=수정&page=1&size=10

#### 5-10. 게시글 승인
PATCH http://localhost:8081/api/boards/4/approve
Content-Type: application/json
Authorization: {{access_token}}

#### 5-10-1. 승인된 게시글 조회
GET http://localhost:8081/api/boards/approved?page=1&size=10

#### 5-11. 게시글 승인 취소
PATCH http://localhost:8081/api/boards/11/disapprove
Content-Type: application/json
Authorization: {{access_token}}

#### 5-11-1. 미승인된 게시글 조회
GET http://localhost:8081/api/boards/unapproved?page=1&size=10

#### 5-12. 5개 인기 랭킹 조회
GET http://localhost:8081/api/boards/ranking

#### 5-13. 10개 인기 검색어
GET http://localhost:8081/api/boards/popular-keywords

#### 5-14 많이 본 게시글 조회
GET http://localhost:8081/api/boards/popular?page=1&size=10