#### 7-1. 댓글 등록
POST http://localhost:8081/api/boards/2/comments
Content-Type: application/json
Authorization: {{access_token}}

{
  "content": "문어"
}

#### 7-2-1. 댓글 단건 조회
GET http://localhost:8081/api/boards/1/comments
Content-Type: application/json
Authorization: {{access_token}}

#### 7-2-2. 댓글 전체 조회
GET http://localhost:8081/api/boards/comments

#### 7-3. 댓글 수정
PATCH http://localhost:8081/api/boards/comments/1
Content-Type: application/json
Authorization: {{access_token}}

{
  "content": "댓글 수정 테스트"
}

#### 7-4. 댓글 삭제
DELETE http://localhost:8081/api/boards/comments/4
Content-Type: application/json
Authorization: {{access_token}}

#### 7-5. 관리자 - 댓글 삭제
DELETE http://localhost:8081/api/boards/admin/comments/1
Content-Type: application/json
Authorization: {{access_token}}

