name: CI/CD Backend

on:
  push:
    branches: ["main"]   # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 3. Gradle 빌드
      - name: Build (Gradle)
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls -al build/libs

      # 4. 산출물(JAR) EC2로 업로드
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/todayter-0.0.1-SNAPSHOT.jar"
          target: "${{ secrets.EC2_PATH_BACKEND }}/build/libs"
          overwrite: true

      # 5. EC2에서 컨테이너 재시작
      - name: Restart app container on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_PATH_BACKEND }}
            if command -v docker compose >/dev/null 2>&1; then
              docker compose restart app || docker compose up -d app
            else
              docker-compose restart app || docker-compose up -d app
            fi
